#!/bin/bash

################################################################
##
##   MySQL Database Backup Script
################################################################

export PATH=/bin:/usr/bin:/usr/local/bin
TODAY=`date +%d-%m-%Y`

################################################################
################## Update below values  ########################

DB_BACKUP_PATH='/u01/backups/kpp'
MYSQL_HOST='localhost'
MYSQL_PORT='3306'
MYSQL_USER='root'
MYSQL_PASSWORD='-pTxs5_DvJaiY2'
DATABASE_NAME='kpp'
BACKUP_RETAIN_DAYS=14   ## Number of days to keep local backup copy

#################################################################

mkdir -p ${DB_BACKUP_PATH}/${TODAY}
echo "Backup started for database - ${DATABASE_NAME}"

#   -p${MYSQL_PASSWORD} \

mysqldump -h ${MYSQL_HOST} \
   -P ${MYSQL_PORT} \
   -u ${MYSQL_USER} \
   -p ${MYSQL_PASSWORD} \
   --single-transaction --quick --skip-lock-tables \
   ${DATABASE_NAME} | gzip > ${DB_BACKUP_PATH}/${TODAY}/${DATABASE_NAME}-${TODAY}.sql.gz

if [ $? -eq 0 ]; then
  echo "Database backup successfully completed"
else
  echo "Error found during backup"
  exit 1
fi


##### Remove backups older than {BACKUP_RETAIN_DAYS} days  #####

DBDELDATE=`date +"%Y%m%d" --date="${BACKUP_RETAIN_DAYS} days ago"`

if [ ! -z ${DB_BACKUP_PATH} ]; then
  cd ${DB_BACKUP_PATH}
  find ./* -type d -ctime +${BACKUP_RETAIN_DAYS} -exec rm -rf {} \;
fi

### End of script ####
